# Generated by Django 5.2.6 on 2025-09-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
