# Generated by Django 5.2.6 on 2025-09-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_order_image_url'),
    ]

    operations = [
    ]
