# Generated by Django 5.2.6 on 2025-09-30 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_add_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='image_url',
        ),
    ]
